{
 "title": "ceph",
 "description": "ceph",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes)-(ceph_cluster_total_used_bytes)",
     "legendFormat": "{{ handler }}"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "{{ handler }}" },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(ceph_osd_op_w_in_bytes[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata ",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "irate(ceph_osd_op_r_out_bytes[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_op_w[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata ",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(ceph_osd_op_r[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms * on (ceph_daemon) group_left(hostname)ceph_osd_metadata",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "ceph_osd_commit_latency_ms * on (ceph_daemon) group_left(hostname)ceph_osd_metadata",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSD Write + Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(rate(ceph_osd_op_w_latency_sum[5m]) / rate(ceph_osd_op_w_latency_count[5m]) >= 0) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata or vector(0)",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "(rate(ceph_osd_op_r_latency_sum[5m]) / rate(ceph_osd_op_r_latency_count[5m]) >= 0) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSD Recovery Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_recovery_ops[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSD Recovery Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ceph_osd_recovery_bytes[5m]) * on (ceph_daemon) group_left(hostname)ceph_osd_metadata",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Monitors in quorum",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(ceph_mon_quorum_status)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Pools",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(ceph_pool_max_avail)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "((ceph_cluster_total_bytes-ceph_cluster_total_used_bytes)/ceph_cluster_total_bytes)*100",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(ceph_osd_in) ", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "OSDs out",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(ceph_osd_up) - count(ceph_osd_in)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(ceph_osd_up)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count((ceph_osd_up) == 0) or vector(0) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Average PGs per OSD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(ceph_osd_numpg)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "MON UP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(ceph_mon_metadata)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "MGR DOWN",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(ceph_mgr_status==0) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  { "title": "Health", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Health" } },
  {
   "title": "New Panel (2)",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "options": {
    "content": "✅ Check the **health status of your cluster**.\n\n✅ Check the health and status of the **Object Storage Daemon (OSD)**: \n \n* **OSD UP**: Total number of OSD running\n* **OSD Down**: OSD not running\n* **OSD IN**: number of OSD inside the cluster\n* **OSD OUT**: Number of OSD outside the cluster\n\n✅ Check that the **number of Monitors in Quorum** is odd and higher than 2. \n\n✅ Check that there are **no managers daemons down**.\n\n✅ Check that there is **at least one Monitor running**."
   }
  },
  { "title": "Health (2)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 }, "options": { "content": "## Capacity" } },
  { "title": "Health (3)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 }, "options": { "content": "## Latency" } },
  { "title": "Health (4)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 }, "options": { "content": "## IOPS & Throughput" } },
  {
   "title": "New Panel (3)",
   "type": "text",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "options": {
    "content": "⛳ If an **OSD Daemon** crashes and comes back online, usually it will be out of sync with other OSD Daemons containing more recent versions of objects in the placement groups. \nWhen this happens, the OSD Daemon goes into recovery mode and seeks to get the latest copy of the data and bring its map back up to date.\n\n✅ Check in these panels the number of recovery operations and bytes recovered by each daemon."
   }
  }
 ]
}